### ISSUE TITLE
Use cURL instead of file_get_contents to access REST API

### ISSUE THREAD

**Issue by ghost** [frkosurf/bbbmw#8]
See http://stackoverflow.com/questions/3629504/php-file-get-contents-very-slow-when-using-full-url for issue.

This is for communication between BBBmw and the BBB server (in index.php).

**Comment by ghost** [comment]
This should be fixed, tested it and deployed on SURFnet BBBmw instance.

**Comment by Frankniesten** [comment]
Tested the new code. BBBMW works fine.

Thanks!
